services:
    # Container da aplicação com PHP-FPM
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        ports:
            - "6001:6001"
        networks:
            - sail
        depends_on:
            - postgres
            - redis

    # Serviço Nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
        networks:
            - sail
        depends_on:
            - laravel.test

    # Serviço PostgreSQL
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - ./.docker/postgres/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - sail

    # Serviço Redis
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - sail

networks:
    sail:
        driver: bridge
